### PR TITLE
Milestone 1 Portfolio: Setup and mobile version skeleton

### PR DESCRIPTION
**Pull request by michael-duke**
## Portfolio Milestone 1: Setup and mobile version skeleton ##

In this milestone I :
- Understood how to parse a Figma design to create a UI.
- Used Flexbox to place elements in the page.
- Build the header portfolio site for mobile version.
- Used images, icons and backgrounds to enhance the look of the website.

### CODE REVIEW

**Comment by michael-duke** [comment]
**Hello Reviewer,**

😃 Happy reviewing. 

Best, Michael

**Review by sumairq — APPROVED** [review]
### Hi @michael-duke , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

- [Optional] It would be nice if you could align the background image similar to the figma template. 😃  
 ### Your Design        
image 

###  Figma Design  
image



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by michael-duke** [comment]
## My favorite movie: The Great Gatsby
@sumairq what can I do to make it more mobile-first, and also I see my background image for the header is a lil off, how could I fix that
I used
```
background-size:  cover /* so the image doesn't squash and it takes good resolution 
background-position: top;

**Comment by michael-duke** [comment]
@sumairq  kindly give me your advice for the optional comment, thank you 😄

**Comment by michael-duke** [comment]
**@sumairq  Kindly 🥇 check the optional suggestion you made so I can merge the PR**
>I made changes using the following:
```
background-size: contain;
background-repeat: no-repeat;

**Pull request merged**
